

import React, { useState } from "react";
import { FilterIcon, SearchIcon, XIcon } from "lucide-react";
import { Drawer } from "../ui/Drawer";
import { Button } from "../ui/Button";
import { cn } from "../../lib/cn";

export interface Filters {search: string;module: string;type: string;priority: string;severity: string;status: string;automation: string;}
export const EMPTY_FILTERS: Filters = { search: "", module: "All", type: "All", priority: "All", severity: "All", status: "All", automation: "All" };
const options = { module: ["All", "Checkout", "Cart", "Payment", "Auth", "Search", "Account"], type: ["All", "Functional", "UI", "API", "Accessibility", "SEO", "Performance", "Security"], priority: ["All", "Critical", "High", "Medium", "Low"], severity: ["All", "Blocker", "Critical", "Major", "Minor", "Trivial"], status: ["All", "passed", "failed", "running", "blocked", "skipped", "cancelled", "not_run"], automation: ["All", "manual", "automated"] };

export function FilterBar({ filters, setFilters, quick }: {filters: Filters;setFilters: (filters: Filters) => void;quick: boolean;}) {const [open, setOpen] = useState(false);const active = Object.entries(filters).filter(([key, value]) => key !== "search" && value !== "All").length;const select = (label: string, key: keyof Filters, show = true) => show && <select aria-label={label} value={filters[key]} onChange={(event) => setFilters({ ...filters, [key]: event.target.value })} className={cn("h-8 rounded-lg border bg-surface px-2.5 text-xs outline-none focus:border-accent", filters[key] === "All" ? "border-line text-ink-2" : "border-accent text-accent")}>{options[key as keyof typeof options].map((value) => <option key={value} value={value}>{value === "All" ? `${label}: All` : labelize(value)}</option>)}</select>;return <><div className="flex flex-wrap items-center gap-2"><div className="flex h-8 w-full items-center gap-2 rounded-lg border border-line bg-surface px-2.5 sm:w-64"><SearchIcon className="h-4 w-4 text-ink-3" /><input value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value })} placeholder="Search cases" aria-label="Search cases" className="w-full bg-transparent text-sm outline-none placeholder:text-ink-3" /></div>{select("Status", "status")}{select("Priority", "priority", !quick)}{!quick && <><span className="hidden lg:block">{select("Module", "module")}</span><span className="hidden lg:block">{select("Automation", "automation")}</span><Button variant="ghost" size="sm" onClick={() => setOpen(true)}><FilterIcon className="h-3.5 w-3.5" /> More filters{active ? ` (${active})` : ""}</Button></>}{(active || filters.search) && <button onClick={() => setFilters(EMPTY_FILTERS)} className="inline-flex h-8 items-center gap-1 rounded-lg px-2 text-xs text-ink-2 hover:bg-surface-2"><XIcon className="h-3.5 w-3.5" /> Clear</button>}</div><Drawer open={open} onClose={() => setOpen(false)} title="Advanced filters" width="max-w-sm" footer={<Button variant="primary" onClick={() => setOpen(false)}>Apply filters</Button>}><div className="space-y-3 p-5">{(["module", "type", "priority", "severity", "status", "automation"] as const).map((key) => <label key={key} className="block"><span className="mb-1 block text-xs font-medium text-ink-2">{key.charAt(0).toUpperCase() + key.slice(1)}</span>{select(key, key)}</label>)}</div></Drawer></>;}
function labelize(value: string) {return value === "not_run" ? "Not Run" : value.charAt(0).toUpperCase() + value.slice(1);}
