

import React from "react";
import { format } from "date-fns";
import { BotIcon, BugIcon, HandIcon, MoreHorizontalIcon } from "lucide-react";
import type { TestCase } from "../../lib/types";
import { StatusInline } from "../ui/StatusBadge";
import { PRIORITY, SEVERITY } from "../../lib/status";
import { cn } from "../../lib/cn";

export function TestCaseTable({ cases, selected, onToggle, onToggleAll, onOpen, selectable }: {cases: TestCase[];selected: Set<string>;onToggle: (id: string) => void;onToggleAll: () => void;onOpen: (testCase: TestCase) => void;selectable: boolean;}) {
  const all = cases.length > 0 && cases.every((testCase) => selected.has(testCase.id));
  const partial = cases.some((testCase) => selected.has(testCase.id));
  return <div className="h-full overflow-auto"><table className="w-full border-separate border-spacing-0 text-sm"><thead><tr className="text-left text-2xs uppercase tracking-wide text-ink-3">{selectable && <Th className="w-10 pl-4"><input type="checkbox" checked={all} ref={(element) => {if (element) element.indeterminate = !all && partial;}} onChange={onToggleAll} aria-label="Select all visible cases" className="h-4 w-4 accent-[rgb(var(--accent))]" /></Th>}<Th>Case ID</Th><Th className="min-w-[240px]">Test case</Th><Th className="hidden md:table-cell">Priority</Th><Th className="hidden xl:table-cell">Severity</Th><Th className="hidden sm:table-cell">Mode</Th><Th>Status</Th><Th className="hidden lg:table-cell">Assignee</Th><Th className="hidden xl:table-cell">Last run</Th><Th className="w-10 pr-4" /></tr></thead><tbody>{cases.map((testCase) => <tr key={testCase.id} tabIndex={0} onKeyDown={(event) => (event.key === "Enter" || event.key === " ") && (event.preventDefault(), onOpen(testCase))} onClick={() => onOpen(testCase)} className={cn("group cursor-pointer hover:bg-surface-2 focus:bg-surface-2", selected.has(testCase.id) && "bg-accent-soft/40")}>{selectable && <Td className="pl-4" onClick={(event) => event.stopPropagation()}><input type="checkbox" checked={selected.has(testCase.id)} onChange={() => onToggle(testCase.id)} aria-label={`Select ${testCase.id}`} className="h-4 w-4 accent-[rgb(var(--accent))]" /></Td>}<Td><span className="font-mono text-2xs text-ink-3">{testCase.code ?? testCase.id}</span></Td><Td><div className="flex max-w-[320px] items-center gap-1.5 truncate font-medium text-ink">{testCase.name}{testCase.defectId && <BugIcon className="h-3 w-3 shrink-0 text-[rgb(var(--fail))]" />}</div><div className="text-2xs text-ink-3">{testCase.module}</div></Td><Td className="hidden md:table-cell"><span className={PRIORITY[testCase.priority]}>{testCase.priority}</span></Td><Td className="hidden xl:table-cell"><span className={SEVERITY[testCase.severity]}>{testCase.severity}</span></Td><Td className="hidden sm:table-cell"><span className="inline-flex items-center gap-1 text-2xs text-ink-2">{testCase.automation === "automated" ? <BotIcon className="h-3.5 w-3.5" /> : <HandIcon className="h-3.5 w-3.5" />}{testCase.automation === "automated" ? "Auto" : "Manual"}</span></Td><Td><StatusInline status={testCase.status} /></Td><Td className="hidden lg:table-cell text-xs text-ink-2">{testCase.assignee ?? "Unassigned"}</Td><Td className="hidden whitespace-nowrap xl:table-cell"><span className="text-2xs text-ink-3">{testCase.lastRun ? format(new Date(testCase.lastRun), "MMM d, HH:mm") : "—"}</span></Td><Td className="pr-4" onClick={(event) => event.stopPropagation()}><button aria-label={`Actions for ${testCase.id}`} className="rounded p-1 text-ink-3 opacity-0 hover:bg-surface hover:text-ink group-hover:opacity-100 focus:opacity-100"><MoreHorizontalIcon className="h-4 w-4" /></button></Td></tr>)}</tbody></table></div>;
}
function Th({ children, className }: {children?: React.ReactNode;className?: string;}) {return <th className={cn("sticky top-0 z-10 border-b border-line bg-surface-2 px-3 py-2.5 font-medium", className)}>{children}</th>;}
function Td({ children, className, onClick }: {children: React.ReactNode;className?: string;onClick?: (event: React.MouseEvent) => void;}) {return <td onClick={onClick} className={cn("border-b border-line px-3 py-2.5 align-middle", className)}>{children}</td>;}


